export const navigationMenus = {
    Super_Admin: [
      { name: "Homepage", path: "/" },
      { name: "Db", path: "/Db" },
      { name: "Employee", path: "/Db/employee" },
      { name: "CandidateProfile", path: "/CandidateProfile" },
      { name: "Attendance", path: "/Attendance" },
    //   {name: "HRattendance", path: "/hrAttendance"},
      { name: "EmployeeAttendance", path: "/EmplyeAtendnc" },
      { name: "ProjectList", path: "/ProjectList" },
      { name: "QuotationList", path: "/QuotationList" },
      { name: "chat", path: "/chat" },
      { name: "Inbox", path: "/Inbox" },
      { name: "SendEmail", path: "/Inbox/send-email" },
      { name: "EmailDetails", path: "/Inbox/email-details" },
      { name: "Calender", path: "/Calender" },
    ],
    Admin: [
        { name: "Homepage", path: "/" },
        { name: "Db", path: "/Db" },
        { name: "CandidateProfile", path: "/CandidateProfile" },
        { name: "Attendance", path: "/Attendance" },
        { name: "EmployeeAttendance", path: "/EmplyeAtendnc" },
        { name: "ProjectList", path: "/ProjectList" },
        { name: "chat", path: "/chat" },
        { name: "Inbox", path: "/Inbox" },
        { name: "SendEmail", path: "/Inbox/send-email" },
        { name: "EmailDetails", path: "/Inbox/email-details" },
        { name: "Calender", path: "/Calender" },
        { name: "Certificate", path: "/Certificate" },
        {name: "HrAttendance", path:"/HrAttendance"},
    ],
    Employee: [
        { name: "Homepage", path: "/" },
        { name: "Db", path: "/Db" },
        { name: "Employee", path: "/Db/employee" },
        { name: "Attendance", path: "/Attendance" },
        { name: "EmployeeAttendance", path: "/EmplyeAtendnc" },
        { name: "ProjectList", path: "/ProjectList" },
        { name: "chat", path: "/chat" },
        { name: "Inbox", path: "/Inbox" },
        { name: "SendEmail", path: "/Inbox/send-email" },
        { name: "EmailDetails", path: "/Inbox/email-details" },
        { name: "Calender", path: "/Calender" },
    ],
    Intern: [
        { name: "Homepage", path: "/" },
        { name: "Db", path: "/Db" },
        { name: "Employee", path: "/Db/employee" },
        { name: "CandidateProfile", path: "/CandidateProfile" },
        { name: "Attendance", path: "/Attendance" },
        { name: "EmployeeAttendance", path: "/EmplyeAtendnc" },
        { name: "ProjectList", path: "/ProjectList" },
        { name: "chat", path: "/chat" },
        { name: "Inbox", path: "/Inbox" },
        { name: "SendEmail", path: "/Inbox/send-email" },
        { name: "EmailDetails", path: "/Inbox/email-details" },
        { name: "Calender", path: "/Calender" },
    ],
  };
  